from typing import Protocol, Any


class SolverProtocol(Protocol):
    def fit(self, env: Any, config: dict) -> None: ...
    def predict(self, observation: dict, deterministic: bool = True) -> dict: ...
    def evaluate(self, env: Any, episodes: int, seed: int) -> dict: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str) -> "SolverProtocol": ...
